{% set name = "geocat-datafiles" %}
{% set version = "2025.7.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geocat_datafiles-{{ version }}.tar.gz
  sha256: fac8c84dfc2cc0d1d8bfedfe33dfecce2b98649f0860863d441ba8455c2d5429

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - geocat.datafiles
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://geocat.ucar.edu/
  summary: 'GeoCAT-datafiles is a Python module that allows users to download sample datasets for use with GeoCAT projects.'
  dev_url: https://github.com/NCAR/{{ name }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyschneck # C. Schneck https://github.com/cyschneck
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
