{% set name = "geocat-datafiles" %}
{% set version = "2025.07.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz # For building from a specific tag's tarball
  sha256: cf10abb7630d7ec2f4768a3382926fecc531e631077ca9277a78126f8a163119
  # git_tag: v{{ version }} # For building from a specific tag
  # git_rev: main # For building from branch for debugging purposes
  # git_url: https://github.com/NCAR/{{ name }}.git

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - python >=3.8                        # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - geocat.datafiles
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://geocat.ucar.edu/
  summary: 'GeoCAT-datafiles is a Python module that allows users to download sample datasets for use with GeoCAT projects.'
  dev_url: https://github.com/NCAR/{{ name }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyschneck # C. Schneck https://github.com/cyschneck
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
